### ISSUE TITLE
Remove polymake default application (switch to "common")

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Polymake.jl#109]
Currently the polymake interpreter is [set to application polytope by default](https://github.com/oscar-system/Polymake.jl/blob/04de15a5b77a55298720bdc7ad86773044921060/src/Polymake.jl#L62
) which is non-obvious for any julia user. We should change the default to application common and use only fully qualified names.

- The automatically generated function calls need to get the corresponding `app::` prefix

- All perlobj calls also need to have the application prefix which we need to lookup in the `@pm` macro (discussed in #100)
 This adds some extra difficulty for the case that someone does `using Polymake.Tropical`, in this case `@pm Polytope{...}(...)` should produce the correct object from application tropical.
  Also we need to throw an error when someone does `using Polymake.Tropical` and `using Polymake.Polytopes` because of the conflicting big object types.

  For this we could introduce a bunch of names (without any functionality) for the generic object types (generated with `list_big_objects`) in each application which we could then use for the type lookup in the macro and to make sure an error is thrown for conflicting applications?

- maybe more?

**Comment by kalmarek** [comment]
* done in #119, see e1169f3 
* `@pm` macro needs fully qualified names at the moment;
* I have (a hacky) code for preparing constructors of `App.BigObject`s with all the bells and whistles (docs, etc), which will just warn user of an unqualified name (in the case of `Polytope` which is the only conflicting name of BigObjects (??); however that code needs to be evaluated at (or after) `__init__()`, cause it needs `Polymake.Main`;
