### ISSUE TITLE
Wrapping Polymake types

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#142]
- [x] Incidence Matrix
- [ ] SparseVector/Matrix
- [x] Tropical numbers
- [ ] Polynomials
- [ ] BitSet
- [ ] Graph

**Comment by sebasguts** [comment]
Good thing. Should we directly convert Polynomials to AbstractAlgebra or Singular Polynomials? I think the others have no real mirror in the OSCAR world yet.

Also, should we try to define a tropical ring in the AbstractAlgebra world?

**Comment by kalmarek** [comment]
I wouldn't go too far with integration yet;
mostly because AA polynomials by default use BigInts; on Singular polynomials I have a very mixed feeling :P 

Sparse things would need to go through SparseArrays types (should be relatively easy to get the basic functionality). `IncidenceMatrix` follows sparse stuff, but I have no good idea, since wrapping basics will be mostly about 0-1 indexing issue.  

@saschatimme how is your sketch implementation of tropical things?

**Comment by saschatimme** [comment]
Did anybody work on the `IncidenceMatrix`?

**Comment by kalmarek** [comment]
I did https://github.com/kalmarek/Polymake.jl/tree/enh/incidencematrix but didn't get too far;

What do you want to do with an `IncidenceMatrix`? You can always do `@pm Common.convert_to{Matrix{Integer}}(...)` if you need access to entries of it.

**Comment by saschatimme** [comment]
This is probably already enough for me :)

**Comment by kalmarek** [comment]
this is tracked in #30
