### ISSUE TITLE
@convert_to macro

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#189]
```julia
Polymake.@convert_to Array{Set{Int}} power_set
```
based on `@pm common.convert_to{PerlType}(power_set)`

**Comment by saschatimme** [comment]
@alexej-jordan  Do we want to do this together on Friday?

**Comment by alexej-jordan** [comment]
@saschatimme sure. I already made the main part work but would love some advice on the details. Friday sounds good

**Comment by saschatimme** [comment]
@alexej-jordan I have to work from home today, but you could open a draft pull request for the changes and then I review it this morning.

**Comment by benlorenz** [comment]
closed with #213
