### ISSUE TITLE
BigObject from another BigObject

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#214]
I tried to mimic this
```perl
polymake > $c = polytope::cube(3);

polymake > $d = new polytope::Cone($c);
```

```julia
BigObject("polytope::Cone", polytope.cube(3))
ERROR: unknown perl subroutine Polymake::Core::BigObject::construct
Stacktrace:
 [1] BigObject(::String, ::Polymake.BigObjectAllocated) at /home/kalmar/.julia/packages/CxxWrap/lDNAy/src/CxxWrap.jl:552
 [2] top-level scope at REPL[15]:1
```
this constructor is called:
```c++
.constructor<const std::string&, const pm::perl::BigObject&>()
```

Two more questions:
* shouldn't we be using `BigObjectType` for `BigObject` construction? what purpose `BigObjectType` serves for now? @benlorenz 
* in jupyter the first line gets stangely truncated if we return something templated, e.g. `@pm polytope.Polytope{QuadraticExtension}(...)` @saschatimme could you have a look?

**Comment by benlorenz** [comment]
This seems to be a bug in polymake that no one noticed for quite a while, but it might be easy to fix. I was about to suggest using `p.cast("type")` instead but this doesn't work either.

Most functions for `BigObject` taking a type can use both the type object or the type string, using the type object is probably slightly more efficient and maybe more elegant. But don't think there is anything where we strictly need the `BigObjectType` right now.

**Comment by kalmarek** [comment]
ok, then, we leave this for `0.3.1`
