### ISSUE TITLE
`nvars` for polynomials is a CxxWrap type

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Polymake.jl#235]
```julia
julia> p = Polymake.Polynomial([1,2],[3 4 5; 6 7 0])
pm::Polynomial<long, long>
2*x_0^6*x_1^7 + x_0^3*x_1^4*x_2^5

julia> Polymake.nvars(p)
CxxWrap.CxxWrapCore.ConstCxxRef{CxxWrap.CxxWrapCore.CxxLong}(Ptr{CxxWrap.CxxWrapCore.CxxLong} @0x00007fefb9f3bac0)
```

**Comment by benlorenz** [comment]
This is returned as a const reference from polymake and this type seems to be not so well integrated in the CxxWrap types.
`unsafe_load` should help, or we adjust the return type of the wrapper function:
```
wrapped.method("nvars", [] (polyT& a) -> pm::Int { return a.n_vars(); });
```

PS: I'm surprised that the default polynomial is `<long,long>` instead of `<Rational,long>`.

**Comment by saschatimme** [comment]
I don't think it is the "default", however, given a polynomial with `Int64` coefficients we automatically make a `<long,long>` polynomial (since this is the "smallest" matching polymake type).

**Comment by saschatimme** [comment]
But it could make sense to always go to rational...

**Comment by benlorenz** [comment]
I would say small types should be upgraded to Rational unless the given coefficients are already a polymake type `pm::Integer` or the type is explicitly specified, but this should be a separate ticket.
