### ISSUE TITLE
Find out which version of polymake we're running

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#272]
@micjoswig asked for this functionality
should be a two-liner function

**Comment by kalmarek** [comment]
@micjoswig 
you can run `Polymake.shell_execute("""print \$Version;""").stdout`, possibly wrapped inside `VersionNumber(...)`.

do you wish this to be added as a separate function/const in `Polymake.jl`?

**Comment by micjoswig** [comment]
Beautiful!

Actually it would be nice to wrap these two (under whatever name fits the Julia/Polymake.jl conventions):

julia> Polymake.shell_execute("""print \$Version;""").stdout
"4.0"

julia> Polymake.shell_execute("""print \$InstallTop;""").stdout
"/home/mic/.julia/packages/Polymake/asr90/deps/usr/share/polymake"

What about "Version" and "InstallTop"?  But everything else is fine, too.

On 30.04.20 11:55, kalmarek wrote:
> @micjoswig 
> you can run `Polymake.shell_execute("""print \$Version;""").stdout`, possibly wrapped inside `VersionNumber(...)`.
> 
> do you wish this to be added as a separate function/const in `Polymake.jl`?
> 

-- 
Prof. Dr. Michael Joswig           <joswig@math.tu-berlin.de>
Technische Universitaet      Institut fuer Mathematik, MA 6-2
Str. des 17. Juni 136                 D-10623 Berlin, Germany
phone +49 (30) 314-75904               fax +49 (30) 314-25047

**Comment by kalmarek** [comment]
closed via #276:
added:
`Polymake.version()` and `Polymake.installTop()`
