### ISSUE TITLE
Cannot construct topaz.vietoris_rips_filtration

### ISSUE THREAD

**Issue by IvanSpirandelli** [oscar-system/Polymake.jl#280]
When I construct a distance matrix as follows:
`distances = Distances.pairwise(Distances.Euclidean(),points_t,points_t,dims=2)` 
where `points_t` is a "Dimension of points X Number of points matrix" 
I am able to create a Vietoris Rips Complex by calling:
`topaz.vietoris_rips_complex(distances, delta)` 
where delta is some float, but I cant construct
`topaz.vietoris_rips_filtration(distances, a, step_size, k)` 
with `a` being a polymake array and `step_size` and `k` a float and an int.

It also does not work by using polymakes `common.distance_matrix(dist, points)` 
with `dist` being: 
`function euclidean_dist(x::Vector{Float64}, y::Vector{Float64})
return sqrt(min(0.0, sum(abs2, x-y)))
end
dist = @cfunction(euclidean_dist, Cdouble, (Ref{Cdouble}, Ref{Cdouble}))
Base.convert(::Type{Polymake.PolymakeType}, ptr::Ptr{Cvoid}) = ptr`

Here we get:
`Cannot pass function value: conversion failed for argument of type Ptr`

**Comment by benlorenz** [comment]
Passing function pointers to polymake is not implemented and would probably be very difficult as this  needs to be wrapped in a proper perl code reference.

For the other variants, please provide some more code to copy or the relevant error messages.

**Comment by IvanSpirandelli** [comment]
I am using Julias Distances Package and then do the following:
```
points = rand(Float64, (12,2))

points_t = transpose(Matrix(points))

distances = Distances.pairwise(Distances.Euclidean(),points_t,points_t,dims=2)

a = Polymake.Array([0,0,0,0,0,0,0,0,0,0,0,0])

topaz.vietoris_rips_filtration(distances, a, 0.3, 1)
```

which results in: 

```
no matching overloaded instance of Polymake::topaz::vietoris_rips_filtration(Matrix<Float, NonSymmetric>, Array<Int>, Float, Int) at -e line 0.
	eval {...} called at -e line 0


Stacktrace:
 [1] internal_call_function(::String, ::CxxWrap.StdLib.StdVectorAllocated{CxxWrap.StdLib.StdString}, ::Array{Any,1}) at /home/ivan/.julia/packages/CxxWrap/lDNAy/src/CxxWrap.jl:552
 [2] call_function(::Type{Polymake.PropertyValue}, ::Symbol, ::Symbol, ::Array{Float64,2}, ::Vararg{Any,N} where N; template_parameters::Array{String,1}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/ivan/.julia/packages/Polymake/kIMyn/src/call_function.jl:19
 [3] call_function(::Symbol, ::Symbol, ::Array{Float64,2}, ::Vararg{Any,N} where N; template_parameters::Array{String,1}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/ivan/.julia/packages/Polymake/kIMyn/src/call_function.jl:25
 [4] vietoris_rips_filtration(::Array{Float64,2}, ::Vararg{Any,N} where N; template_parameters::Array{String,1}, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/ivan/.julia/packages/Polymake/kIMyn/src/meta.jl:273
 [5] vietoris_rips_filtration(::Array{Float64,2}, ::Polymake.ArrayAllocated{CxxWrap.CxxWrapCore.CxxLong}, ::Vararg{Any,N} where N) at /home/ivan/.julia/packages/Polymake/kIMyn/src/meta.jl:273
 [6] top-level scope at In[7]:1
```

**Comment by benlorenz** [comment]
The function needs an explicit template parameter for the coefficient type:
```julia
julia> x = @pm topaz.vietoris_rips_filtration{Rational}(distances, a, 0.3, 1)
PropertyValue wrapping polymake::topaz::Filtration<pm::SparseMatrix<pm::Rational, pm::NonSymmetric> >
(0,0,0),(0,0,1),(0,0,2),(0,0,3),(0,0,4),(0,0,5),(0,0,6),(0,0,7),(0,0,8),(0,0,9),(0,0,10),(0,0,11),(1,1,7),(1,1,13),(1,1,18),(1,1,21),(1,1,26),(1,1,32),(1,1,33),(1,1,36),(1,1,48),(1,1,49),(1,1,50),(1,1,51),(1,1,58),(1,1,59),(1,1,63),(1,1,65),(2,1,1),(2,1,2),(2,1,11),(2,1,12),(2,1,14),(2,1,16),(2,1,17),(2,1,19),(2,1,20),(2,1,22),(2,1,24),(2,1,25),(2,1,27),(2,1,28),(2,1,29),(2,1,31),(2,1,34),(2,1,35),(2,1,37),(2,1,42),(2,1,43),(2,1,45),(2,1,46),(2,1,54),(2,1,55),(2,1,57),(2,1,64),(3,1,0),(3,1,3),(3,1,5),(3,1,6),(3,1,8),(3,1,9),(3,1,10),(3,1,15),(3,1,23),(3,1,30),(3,1,38),(3,1,40),(3,1,41),(3,1,44),(3,1,47),(3,1,52),(3,1,53),(3,1,56),(3,1,60),(3,1,61),(3,1,62),(4,1,4),(4,1,39),
```

I'm not sure if this is possible without the `@pm` macro at the moment.

**Comment by kalmarek** [comment]
no, functions in julia are no longer parametrized, so it's not possible without `@pm` macro.
What we could do is to provide a better error message (e.g. I was fooled by the present message). Currently I don't see how could we leverage generated jsons to do it within julia, is is possible to do this from polymake? Ideas?

**Comment by benlorenz** [comment]
> no, functions in julia are no longer parametrized, so it's not possible without `@pm` macro.

With #285 (adapted from the bigobjects) it works without the macro, but the macro is still available and useful as fallback for non-mapped types.

> What we could do is to provide a better error message (e.g. I was fooled by the present message). Currently I don't see how could we leverage generated jsons to do it within julia, is is possible to do this from polymake? Ideas?

I added some more stuff in the json for the mandatory type parameters that is used in meta.jl in #285. Is this better?
```
ERROR: MethodError: no method matching Polymake.topaz.vietoris_rips_filtration(::Array{Float64,2}, ::Polymake.ArrayAllocated{Int64}, ::Float64, ::Int64)
```

We could even generate dummy functions there for this case that print a nice error.

**Comment by kalmarek** [comment]
I'm not sure about dummy functions (extending precompilation times which are already not insignificant), but if there weren't too many functions that require mandatory templates we could give it a try.

**Comment by benlorenz** [comment]
About 50 functions, most of them in application tropical.

**Comment by benlorenz** [comment]
Closing this now:
Passing function pointers will not be implemented any time soon.
Templated functions can now be called without `@pm` and those requiring a template will give a better error message if it is missing.
