### ISSUE TITLE
wrap pm::Array<std::pair<Int, Int>>

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#283]
needed for spanning tree edges, needed for Perles irrational polytope example

**Comment by kalmarek** [comment]
@IvanSpirandelli you'll need this to have be able to access 
```julia
julia> vrf = @pm topaz.vietoris_rips_filtration{Rational}(distances, a, 0.2, 1);

julia> pershom = topaz.persistent_homology(vrf)
PropertyValue wrapping pm::Array<std::__cxx11::list<std::pair<long, long>, std::allocator<std::pair<long, long> > >>
(...)
```

**Comment by IvanSpirandelli** [comment]
That would be great!

**Comment by benlorenz** [comment]
Please note that there is an additional `std::list` involved in the homology. But this could probably be done in one go.
