### ISSUE TITLE
wipe polymake_user/wrappers at build time

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Polymake.jl#286]

**Comment by benlorenz** [comment]
Finding the correct `wrappers.x` might involve some extra work, deleting all of them could cause issues when there is a different clone of `Polymake.jl` still running.

**Comment by benlorenz** [comment]
I just noticed that we already do this here https://github.com/oscar-system/Polymake.jl/blob/1434acaea7ce28f6aa83d0d8bec84dca0d289222/deps/build.jl#L111
This is run during build and even during startup, but when using the BinaryBuilder installation.

**Comment by kalmarek** [comment]
this what I came up with:
```julia
depsjl = :(
        ENV["PERL5LIB"]=$perllib;
        ENV["POLYMAKE_USER_DIR"] = abspath(joinpath(Pkg.depots1(),"polymake_user"));
        ENV["PATH"] = ENV["PATH"]*":"*joinpath($pm_bin_prefix,"bin");
        )
    eval(depsjl)

    rex = Regex("\\s+'$(@__DIR__).*'\\s?=>\\s?'(?<wrappers_dir>wrappers\\.\\d+)'\\s?,?")
    for l in readlines(joinpath(ENV["POLYMAKE_USER_DIR"], "customize.pl"))
        m = match(rex, l)
        if m !== nothing && m[:wrappers_dir] !== nothing
            wrappers = joinpath(ENV["POLYMAKE_USER_DIR"], m[:wrappers_dir])
            @info "Removing $(wrappers)"
            # rm(wrappers, force=true, recursive=true)
        end
    end
```

**Comment by benlorenz** [comment]
Something like `if Base.Filesystem.isdir(user_dir)` should probably be in there because this will run before any polymake and the directory might not exist. But seems very reasonable otherwise and works as expected:
```
[ Info: Removing /home/lorenz/.julia/polymake_user/wrappers.2
```

**Comment by kalmarek** [comment]
`rm` with `force=true` parameter doesn't fail for non-existent directories. Something like:
```julia
if m !== nothing && m[:wrappers_dir] !== nothing
            wrappers = joinpath(ENV["POLYMAKE_USER_DIR"], m[:wrappers_dir])
            isdir(wrappers) && @info "Removing $(wrappers)"
            # rm(wrappers, force=true, recursive=true)
end
```
or do you prefer the `rm` inside `if` as well?

**Comment by benlorenz** [comment]
I meant outside of the loop before doing `readlines` on a file in that directory (user-dir, not wrapper). But probably `isfile` on the file itself would be better.

**Comment by kalmarek** [comment]
indeed.
```julia
    rex = Regex("\\s+'$(@__DIR__).*'\\s?=>\\s?'(?<wrappers_dir>wrappers\\.\\d+)'\\s?,?")
    customize_file = joinpath(ENV["POLYMAKE_USER_DIR"], "customize.pl")
    if isfile(customize_file)
        for l in readlines()
            m = match(rex, l)
            if m !== nothing && m[:wrappers_dir] !== nothing
                wrappers = joinpath(ENV["POLYMAKE_USER_DIR"], m[:wrappers_dir])
                @info "Removing $(wrappers)"
                # rm(wrappers, force=true, recursive=true)
            end
        end
    end
```
do you mind if I push to #287 ?

**Comment by benlorenz** [comment]
no, I don't mind, go ahead, then you can even review it yourself :)
