### ISSUE TITLE
GitHub Pages build not triggered

### ISSUE THREAD

**Issue by alexej-jordan** [oscar-system/Polymake.jl#317]
The documentation still can not be accessed after merging the branch into master. Looking into what happened during the workflow shows this warning at the end of the deployment process:

> ┌ Warning: Currently the GitHub Pages build is not triggered when using `GITHUB_TOKEN` for authentication. See issue #1177 (https://github.com/JuliaDocs/Documenter.jl/issues/1177) for more information.

the last comment (https://github.com/JuliaDocs/Documenter.jl/issues/1177#issuecomment-640998242) points out that our setup actually should work. most of the commentors (notably before others claimed this solved) suggested to use ssh keys instead, which appears rather inconvenient in this context to me.

**Comment by benlorenz** [comment]
There is `dev` documentation at https://oscar-system.github.io/Polymake.jl/dev/ but no stable docs yet, probably because it needs to run for a release tag for that.

I don't really know about that warning, but docs are deployed in this log: https://github.com/oscar-system/Polymake.jl/runs/955391821?check_suite_focus=true
Does anything else need to happen?

**Comment by alexej-jordan** [comment]
you are most probably right about needing a versioned release before this can work. we should probably add some more badges for the `README` though, e.g. the `dev` documentation.

and yes, within this log, in the `build and deploy` step, line 32, there is this warning. but now it rather looks like an outdated standard warning

**Comment by kalmarek** [comment]
I'm fine with adding ssh key for deploy; The point is that using GITHUB_TOKEN will not trigger other GH actions, hence if we tag no documentation will be build;

I can add those secrets/keys if you wish, but we already had a similar argument about `CompatHelper` #259 which was left hanging for the same reason

**Comment by benlorenz** [comment]
Lets wait for the next tag before we do anything further. According to that ticket it did work in many cases as soon as some manual commit was on the gh-pages branch.

**Comment by benlorenz** [comment]
This can be closed, release and master docs are being built, see https://github.com/oscar-system/Polymake.jl/tree/gh-pages .
