### ISSUE TITLE
Issue building Polymake.jl on aarch64.

### ISSUE THREAD

**Issue by rbehrends** [oscar-system/Polymake.jl#323]
I've been working with getting Oscar to build on ARM architectures, and there seem to be some issues specific to that architecture. Specifically, when doing `Pkg.add("Oscar")` I get the following Polymake-related error:

```
┌ Error: Error building `Polymake`: 
│ [ Info: Linux(:aarch64, libc=:glibc, compiler_abi=CompilerABI(:gcc7, :cxx11))
│ ERROR: LoadError: Your platform aarch64-linux-gnu-gcc7-cxx11 is not supported by this package!
│ If you already have a polymake installation you need to set the environment variable `POLYMAKE_CONFIG`.
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /tmp/devjulia/packages/Polymake/qn5DS/deps/build.jl:84
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /tmp/devjulia/packages/Polymake/qn5DS/deps/build.jl:74
└ @ Pkg.Operations /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

The issue seems to be simply that there is no binary package for that architecture (Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-1018-raspi aarch64)).

**Comment by rbehrends** [comment]
Update: this happens only when using the stable version of Oscar. `Pkg.add("Oscar")` constrains Polymake.jl to be an older version. The newest version of Polymake.jl does not have this problem, though end users may still see this issue.

**Comment by benlorenz** [comment]
The latest version of polymake will also not work on ARM (both 32bit and 64bit) right now, as there are no binaries for perl or polymake, which both are rather difficult to cross-compile. I will try to have a look if I can pre-generate the necessary files on some ARM VM / Hardware but that might take a while.

With the Pkg Artifacts there is (unfortunately) no error when using the artifact on an unsupported platform.

**Comment by fingolfin** [comment]
@benlorenz we have ARM machines (well, Raspberry PIs ;-) ) in Kaiserslautern, both 32 and 64 bit -- if it would help you to get SSH access to them, we can arrange that (talk to @hannes14).

**Comment by fingolfin** [comment]
Just to be clear, I am *not* saying or implying this is a priority! Just that in case your (or somebody else) wants to work on this and would benefit from SSH to ARM machines, we can provide it.

**Comment by benlorenz** [comment]
I already created some initial configuration files in a qemu-chroot, but the difficult part is that it needs to be adapted to match the environment that BinaryBuilder is using for compilation (glibc version, ...). But that sysroot is very bare and not made for running stuff within.
(the perl config.sh stores way too much information, see e.g. the [macos config.sh](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/Perl/bundled/patches/config-x86_64-apple-darwin14.sh))

**Comment by benlorenz** [comment]
This should work with Polymake.jl 0.6.2 (but I have not tested aarch64-linux yet).
Supported platforms for the binaries can be seen here: https://github.com/JuliaBinaryWrappers/polymake_jll.jl#platforms
