### ISSUE TITLE
cannot precompile

### ISSUE THREAD

**Issue by fieker** [oscar-system/Polymake.jl#328]
```
[ Info: Generating module matroid
ERROR: LoadError: InitError: MethodError: no method matching String(::Base.RefValue{String})
Closest candidates are:
  String(::String) at boot.jl:321
  String(::Array{UInt8,1}) at strings/string.jl:39
  String(::Base.CodeUnits{UInt8,String}) at strings/string.jl:77
  ...
Stacktrace:
 [1] __init__() at /home/fieker/.julia/packages/Polymake/Zj1DQ/src/Polymake.jl:99
 [2] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
```

**Comment by fieker** [comment]
sorry, originally
[ Info: Generating module matroid
ERROR: LoadError: InitError: MethodError: no method matching *(::String, ::Base.RefValue{String})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  *(::Union{AbstractChar, AbstractString}, ::Union{AbstractChar, AbstractString}...) at strings/basic.jl:251
  *(::Union{Regex, AbstractChar, AbstractString}, ::Union{Regex, AbstractChar, AbstractString}...) at regex.jl:656
  ...
Stacktrace:
 [1] __init__() at /home/fieker/.julia/packages/Polymake/Zj1DQ/src/Polymake.jl:99
 [2] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [3] _require_from_serialized(::String) at ./loading.jl:749


"Fix": 
    ENV["PATH"] *= ":" * Ninja_jll.PATH[]
    ENV["PATH"] *= ":" * Perl_jll.PATH[]
add the [] at the end

**Comment by benlorenz** [comment]
That should be fixed in 0.5.2, see https://github.com/oscar-system/Polymake.jl/pull/325/files
(with a `isa` because at that time only some jll wrappers were using the new style)

**Comment by fieker** [comment]
On Mon, Nov 02, 2020 at 06:17:58AM -0800, Benjamin Lorenz wrote:
> That should be fixed in 0.5.2, see https://github.com/oscar-system/Polymake.jl/pull/325/files
> (with a `isa` because at that time only some jll wrappers were using the new style)
> 
Julia needs to improve those versions. I did an update just before it
failed to work - but I am on 5.1 not 5.2. Now I shall force 5.2...

Thanks

**Comment by fingolfin** [comment]
@fieker can this be closed now?

**Comment by fieker** [comment]
I close it
