### ISSUE TITLE
Define a polytope as the intersection of halfspaces

### ISSUE THREAD

**Issue by ZacharieALES** [oscar-system/Polymake.jl#346]
In the original polymake it is possible to define a polyhedron as the intersection of several halfspaces (i.e., using linear constraints ax <= b). Here is an example from the documentation:
`$p4 = new Polytope(INEQUALITIES=>[[1,1,0],[1,0,1],[1,-1,0],[1,0,-1],[17,1,1]]);`

Is it possible to do the same with Polymake.jl? I did not find the syntax in the documentation or the examples.

**Comment by benlorenz** [comment]
Please check the [syntax translation page](https://oscar-system.github.io/Polymake.jl/stable/examples/#Big-objects-and-properties:). It does not list `INEQUALITIES` explicitly but all polymake properties can be used in the same way, so for your example:
```julia
julia> p4 = polytope.Polytope(INEQUALITIES=[1 1 0; 1 0 1; 1 -1 0; 1 0 -1; 17 1 1])
type: Polytope<Rational>

INEQUALITIES
   1   1   0
   1   0   1
   1  -1   0
   1   0  -1
  17   1   1
   1   0   0


julia> p4.VERTICES
pm::Matrix<pm::Rational>
1 1 -1
1 1 1
1 -1 1
1 -1 -1
```

**Comment by ZacharieALES** [comment]
Great, thank you!

Since I am a beginner in Polymake, I was indeed only looking for explicit mentions of "inequalities" or "half space" in the documentation. Maybe it could be added in one sentence in the documentation that all properties are compatible and then list the most important ones.
