### ISSUE TITLE
using Polymake crashes

### ISSUE THREAD

**Issue by ZacharieALES** [oscar-system/Polymake.jl#347]
I am using Julia 1.4.1. 
I just installed polymake using
`julia> using Pkg; Pkg.add("Polymake")`

When I try to use the package I get an error:
`julia> using Polymake

signal (6): Aborted
in expression starting at REPL[2]:1
gsignal at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fb1f99b2b61)
jl_method_table_insert at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
unknown function (ip: 0x7fb1f9a55447)
jl_restore_incremental at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
_include_from_serialized at ./loading.jl:681
_require_search_from_serialized at ./loading.jl:781
_require at ./loading.jl:1006
require at ./loading.jl:927
require at ./loading.jl:922
unknown function (ip: 0x7fb1f9a5e113)
unknown function (ip: 0x7fb1f9a5f266)
unknown function (ip: 0x7fb1f9a5f3c8)
jl_toplevel_eval_in at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
eval at ./boot.jl:331
eval_user_input at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
macro expansion at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
#26 at ./task.jl:358
unknown function (ip: 0x7fb1f9a49cbb)
unknown function (ip: (nil))
Allocations: 15749719 (Pool: 15745483; Big: 4236); GC: 12
Aborted (core dumped)
`

Do you know why? According to the documentation it seemed to be enough to install it.

**Comment by benlorenz** [comment]
Can you try:
```julia
using Pkg;
Pkg.add(PackageSpec(name="CxxWrap",version="0.11.0"));
Pkg.pin("CxxWrap");
```
This is a known bug / incompatibility of Polymake + CxxWrap >=0.11.1 + julia <= 1.4.1. It does not happen with 1.4.2 and later versions, so you can either use the above commands or install some newer julia binaries.

**Comment by ZacharieALES** [comment]
It worked, thanks!
