### ISSUE TITLE
Frequent tiny allocations

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Polymake.jl#392]
I was wondering why `dim` on a polyhedral fan in Oscar takes 5 allocations:
```
julia> PF = PolyhedralFan([1 0; 0 1; -1 -1], IncidenceMatrix([[1, 2], [3]]))
A polyhedral fan in ambient dimension 2

julia> @time dim(PF)
  0.000096 seconds (5 allocations: 96 bytes)
2
```
Upon investigating, I found the following sources, and have a few suggestions on how we might avoid them. I realize you are probably aware of this already, but perhaps we can discuss whether it'd be worth doing it in your eyes or not.

1. one allocation for converting the symbol `:FAN_DIM` to a string in `getproperty(::BigObject, ::Symbol)`, so it can ultimately be passed to `internal_give` in `libpolymake-julia`: <https://github.com/oscar-system/Polymake.jl/blob/f4972bcac058980b2de61c59c659aa97f1f2e908/src/perlobj.jl#L63-L69> This could be addressed by changing `internal_give` to take a `jl_sym_t *` (which can be turned into a char pointer via `jl_symbol_name`).

   Experimental verification:

       julia> @time Polymake.give(PMO, "FAN_DIM");
         0.000086 seconds (4 allocations: 72 bytes)

2. one allocation by `typeinfo_string` called from `convert_from_property_value`. This could perhaps be addressed by making that function return a `jl_sym_t *`. Then for the "common" (?) cases (`"bool"`, `"Int"`, etc.) we can return precomputed `jl_sym_t *`, and only for the "custom" typename is it necessary to insert a `jl_symbol(cxxstr.c_str())` call for the string.
   
   Experimental verification:

       julia> return_obj = Polymake.internal_give(PMO, "FAN_DIM");
       
       julia> @time Polymake.typeinfo_string(return_obj,true)
         0.000040 seconds (1 allocation: 16 bytes)
       "Int"

3. Also in `convert_from_property_value`, the line `T = Symbol(replace(type_name," "=>""))` causes another allocation (even if one changes it to `T = Symbol(type_name)`. Of course this would be resolved by point 2.

4. This leaves two allocations calling `Polymake.internal_give`. One of them is for converting a Julia string to a `std::string` allocated on the heap. Again, this could be avoided by passing a `jl_sym_t *`.

   Experimental verification:

       julia> @time Polymake.internal_give(PMO, "FAN_DIM");
         0.000082 seconds (2 allocations: 32 bytes)
       
       julia> prop = Polymake.CxxWrap.StdString("FAN_DIM"); @time Polymake.internal_give(PMO, prop);
         0.000064 seconds (1 allocation: 16 bytes)

5. This leaves one allocation; I believe (but have not verified) that this is for the return value of `Polymake.internal_give`, which on the Julia side has type `Polymake.PropertyValueAllocated`, and I think it's that object which gets allocated. I guess it can't be avoided.

---

Some naive benchmarking (ignoring all the other things e.g. `give()` does):
```
julia> @btime dim(PF);
  5.125 μs (5 allocations: 96 bytes)

julia> @btime Polymake.internal_give(PMO, "FAN_DIM");
  3.198 μs (2 allocations: 32 bytes)

julia> prop = Polymake.CxxWrap.StdString("FAN_DIM"); @btime Polymake.internal_give(PMO, prop);
  2.972 μs (1 allocation: 16 bytes)
```

**Comment by fingolfin** [comment]
A maybe more egregious example (again in Oscar):
```
julia> c = cube(2)
A polyhedron in ambient dimension 2

julia> m = c.pm_polytope.VERTICES
pm::Matrix<pm::Rational>
1 -1 -1
1 1 -1
1 -1 1
1 1 1

julia> @btime matrix(QQ,vertices(c));
  37.541 μs (268 allocations: 9.73 KiB)

julia> @btime Matrix{fmpq}(c.pm_polytope.VERTICES);
  27.417 μs (272 allocations: 12.53 KiB)

julia> @btime Matrix{Int}(c.pm_polytope.VERTICES); # expect this to use less memory, but... it's worse?!
  27.666 μs (296 allocations: 13.47 KiB)
```

**Comment by benlorenz** [comment]
For now just some quick comments on this, we will keep this in mind but this is rather low priority for us right now.

1. I don't think it is worth the effort to reduce the rather few allocations for the `give` operation, some of these suggestions might also just move allocations away from julia (so that they cannot be counted this way). Additionally, any `give` operation (or basically anything involving `BigObject`) will involve some perl code that will quire surely trigger some more allocations that we won't be able to count from julia. 
   Depending on the polytope, asking for `dim` might even trigger multiple LP computations in the background. At least some parts of the required allocations for this computation (gmp numbers) are shown by `@time` (not by `@btime`) on the first `dim` call but (as expected) not for any further calls:
```julia
julia> p = Polyhedron(facets(c));

julia> @time dim(p);
  0.008599 seconds (1.65 k allocations: 13.969 KiB)

julia> @time dim(p);
  0.000156 seconds (6 allocations: 160 bytes)
```

2. There is definitely something we can and should do about the `fmpq` conversion, currently it goes through a rather generic path via `BigInt`s for numerator and denominator. So far there is no special C++ code for such conversions and that would probably help quite a bit. (The original design goal of Polymake.jl was to produce a working version that works well with most of the interfaces / abstract types from julia, before it was really agreed upon what types would be used for Oscar)
   At some point we might want to make it possible to use `fmpz` and `fmpq` directly in `polymake` instead of our own GMP-based `Integer` and `Rational` types, but since we currently store `+/- inf` within the gmp struct this is unfortunately not a simple replacement.

**Comment by fingolfin** [comment]
Thank you for your comments!

> For now just some quick comments on this, we will keep this in mind but this is rather low priority for us right now.

Fair enough. It is not urgent at all, just wanted to have the discussion somewhere :-).

> 
> 1. I don't think it is worth the effort to reduce the rather few allocations for the `give` operation, some of these suggestions might also just move allocations away from julia (so that they cannot be counted this way).

I agree that this moves some allocations from Julia to C++, but not only (it also avoids some). And I think this is still worthwhile: e.g. instead of allocating a `std::string` on the heap, it can allocate it on the stack. And after the call to `give` finished, it can immediately free it, cheaply. While in the current setup, lots of tiny objects are created, which create pressure on the GC, and in tight loops this can become severe.

> Additionally, any `give` operation (or basically anything involving `BigObject`) will involve some perl code that will quire surely trigger some more allocations that we won't be able to count from julia.

Sure, but it'll do that anyway.

>    Depending on the polytope, asking for `dim` might even trigger multiple LP computations in the background.

But to my understanding the result is cached, so this only happens the first time around, right? Subsequent call are cheap (or *could be* cheap)...

Of course we could simply also cache this kind of data in Oscar, by adding an `@attr` annotation.

> At least some parts of the required allocations for this computation (gmp numbers) are shown by `@time` (not by `@btime`) on the first `dim` call but (as expected) not for any further calls:
> 
> ```julia
> julia> p = Polyhedron(facets(c));
> 
> julia> @time dim(p);
>   0.008599 seconds (1.65 k allocations: 13.969 KiB)
> 
> julia> @time dim(p);
>   0.000156 seconds (6 allocations: 160 bytes)
> ```

Sure, fair enough. But that's one time overhead; I am concerned about the speed of accessing cached results here. Of course in many practical applications this is irrelevant, but in certain ways of writing code, it isn't.

> 
>  2. There is definitely something we can and should do about the `fmpq` conversion, currently it goes through a rather generic path via `BigInt`s for numerator and denominator. So far there is no special C++ code for such conversions and that would probably help quite a bit.

OK. Would it make sense to put this into a separate issue?

> (The original design goal of Polymake.jl was to produce a working version that works well with most of the interfaces / abstract types from julia, before it was really agreed upon what types would be used for Oscar)

Understood, and I 100% agree with this approach, and think y'all did a great job on it!

>    At some point we might want to make it possible to use `fmpz` and `fmpq` directly in `polymake` instead of our own GMP-based `Integer` and `Rational` types, but since we currently store `+/- inf` within the gmp struct this is unfortunately not a simple replacement.

@fieker and me would like to be able to store +/- inf in `fmpz` and `fmpq`, too. See also https://github.com/Nemocas/Nemo.jl/pull/855

**Comment by fingolfin** [comment]
Thanks to @alexej-jordan this has improved considerably. E.g. my `cube` example got a lot faster and uses less allocations -- except, oddly (?) for the final convert to `Matrix{Int}`:
```
julia> c = cube(2)
A polyhedron in ambient dimension 2

julia> @btime matrix(QQ,vertices(c));
  23.125 μs (133 allocations: 1.98 KiB)

julia> @btime Matrix{fmpq}(c.pm_polytope.VERTICES);
  11.666 μs (76 allocations: 1.12 KiB)

julia> @btime Matrix{Int}(c.pm_polytope.VERTICES);
  22.875 μs (292 allocations: 12.58 KiB)
```
Of course the last example is also rather unnatural. So this is not a complain. I am just surprised it turns out to be slower than the conversion to `fmpq`?

**Comment by fingolfin** [comment]
very nice. thank you for working on this!
