### ISSUE TITLE
Update JLL for Julia 1.9

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Polymake.jl#394]
The JLL needs to be rebuilt to support Julia nightly which is no at version 1.9. I already updated libjulia_jll and libcxxwrap_julia.

Perhaps we can also show a better error message what's going on (see https://github.com/oscar-system/GAP.jl/issues/789 for details on that)

**Comment by benlorenz** [comment]
Tests [ran successfully](https://github.com/oscar-system/Polymake.jl/runs/5326576646?check_suite_focus=true) with `Julia Version 1.9.0-DEV.56`.
