### ISSUE TITLE
rand_sphere is gone

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Polymake.jl#66]
Dear Sebastian,

I do appreciate your current effort, and I am all in favor of the idea to move the functions from application polytope to its own module.

Yet I am currently working on stuff, preparing for the upcoming OSCAR meeting.  For this I need a tiny bit more stability.  It's fine to move stuff around, but currently, e.g., rand_sphere does not exist any more in spite of being listed in the temporary json.

I am not sure how this test logic is supposed to work.  Should I create a test from the script that I am working on?  How so?  Or should I create a new directory such that people could check by hand?

-- Michael

**Comment by kalmarek** [comment]
It's in `polytope` namespace:
```julia
julia> polytope.rand_sphere(3,4)
type: Polytope<Rational>
description: Random spherical polytope of dimension 3; seed=15941090982510394030; precision=default


POINTS
1 978225498623963/1125899906842624 -1977390434256485/4503599627370496 -8242464313572267/36028797018963968
1 8925727924844893/18014398509481984 2250498769468559/9007199254740992 -3746589747895351/4503599627370496
1 -3466137233946797/4503599627370496 -4655065531865363/9007199254740992 6753835654037289/18014398509481984
1 -2440870189980629/9007199254740992 -6074024954710259/18014398509481984 -1015107339941969/1125899906842624


CONE_AMBIENT_DIM
4

BOUNDED
true

```

**Comment by micjoswig** [comment]
???
julia> polytope.
AMBIENT_DIM           MINKOWSKI_CONE_COEFF   eval
CD_INDEX              bipyramid              include
DIM                   cube                   placing_triangulation
julia> polytope.rand_sphere(3,20)
ERROR: UndefVarError: rand_sphere not defined

I am at 12ca98234 master.

**Comment by kalmarek** [comment]
probably You need to `] build Polymake`
transformation JSON → julia happens at build time, check if `./src/generated/polytope.jl` is present

(and if nothing works You can always do `Polymake.call_func(:rand_sphere, 3, 20)`)

**Comment by micjoswig** [comment]
Indeed. Sorry. Thanks.
