### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by saschatimme** [oscar-system/Polymake.jl#9]
How will we document this package? Can we reuse the Polymake docstrings? Do we just delegate the user to the Polymake documentation? How do we then deal with API differences? Do we write everything by hand ☹️ ?

**Comment by sebasguts** [comment]
We certainly have to document every function that is not automatically generared by hand, possibly (for data structures for example) linking to the Polymake manual.

I would start by documenting all functions that do not "really" appear in Polymake, and then later think about how to provide possible references.
